name: Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0
      
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List Repository File
        run: ls ${{ github.workspace }}
      
      - name: Install Dependencies
        run: poetry 

      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.0

      - name: Run Tests
        env:
          pytest_github_report: true
          pytest_report_title: "Basel Test Result"
        run: poetry run coverage run -m pytest -vv

      - run: echo "TEST_COVERAGE_TOTAL=$(poetry run coverage --format==total)" >> $GITHUB_ENV

      - name: Print test coverage report
        run: poetry run coverage report

      - name: Check Tests Coverage Percent
        if: ${{TEST_COVERAGE_TOTAL}} < 80
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Tests Coverage less than 80 %')
